# audit/constants.py

# Evaluation lifecycle
EVALUATION_ATTEMPT = "EVALUATION_ATTEMPT"
EVALUATION_SUCCESS = "EVALUATION_SUCCESS"
EVALUATION_VALIDATION_FAIL = "EVALUATION_VALIDATION_FAIL"

# Billing events
BILLING_SUBSCRIPTION_APPLIED = "BILLING_SUBSCRIPTION_APPLIED"
BILLING_CREDIT_DEDUCTED = "BILLING_CREDIT_DEDUCTED"
BILLING_INSUFFICIENT_CREDIT = "BILLING_INSUFFICIENT_CREDIT"

# System protection
THROTTLE_TRIGGERED = "THROTTLE_TRIGGERED"