# Evaluation events
EVALUATION_ATTEMPT = "EVALUATION_ATTEMPT"
EVALUATION_SUCCESS = "EVALUATION_SUCCESS"
EVALUATION_VALIDATION_FAIL = "EVALUATION_VALIDATION_FAIL"

# Billing events
BILLING_CREDIT_DEDUCTED = "BILLING_CREDIT_DEDUCTED"
BILLING_INSUFFICIENT_CREDIT = "BILLING_INSUFFICIENT_CREDIT"
CREDIT_PURCHASE_CREATED = "CREDIT_PURCHASE_CREATED"

# Payment events
PAYMENT_WEBHOOK_RECEIVED = "PAYMENT_WEBHOOK_RECEIVED"
PAYMENT_VERIFIED = "PAYMENT_VERIFIED"
PAYMENT_FAILED = "PAYMENT_FAILED"
PAYMENT_MANUAL_SUBMITTED = "PAYMENT_MANUAL_SUBMITTED"
PAYMENT_MANUAL_APPROVED = "PAYMENT_MANUAL_APPROVED"
PAYMENT_MANUAL_REJECTED = "PAYMENT_MANUAL_REJECTED"

# Security events
LOGIN_FAILED = "LOGIN_FAILED"
THROTTLE_TRIGGERED = "THROTTLE_TRIGGERED"
SUSPICIOUS_ACTIVITY = "SUSPICIOUS_ACTIVITY"

# Usage events
SESSION_STARTED = "SESSION_STARTED"
SESSION_ENDED = "SESSION_ENDED"
PAGE_VIEW = "PAGE_VIEW"
INTERVIEW_STARTED = "INTERVIEW_STARTED"
INTERVIEW_SAVED = "INTERVIEW_SAVED"
INTERVIEW_SUBMITTED = "INTERVIEW_SUBMITTED"
INTERVIEW_ABANDONED = "INTERVIEW_ABANDONED"
REPORT_VIEWED = "REPORT_VIEWED"
REPORT_VIEW_FAILED = "REPORT_VIEW_FAILED"
BILLING_PAGE_VIEWED = "BILLING_PAGE_VIEWED"
CREDIT_PURCHASE_INITIATED = "CREDIT_PURCHASE_INITIATED"
RAPID_PAGE_REQUESTS = "RAPID_PAGE_REQUESTS"
BOT_SUSPECTED = "BOT_SUSPECTED"

# Existing platform-specific audit events retained for compatibility.
BILLING_SUBSCRIPTION_APPLIED = "BILLING_SUBSCRIPTION_APPLIED"
BILLING_QA_BYPASS_APPLIED = "BILLING_QA_BYPASS_APPLIED"

CANONICAL_EVENT_TYPES = [
	EVALUATION_ATTEMPT,
	EVALUATION_SUCCESS,
	EVALUATION_VALIDATION_FAIL,
	BILLING_CREDIT_DEDUCTED,
	BILLING_INSUFFICIENT_CREDIT,
	CREDIT_PURCHASE_CREATED,
	PAYMENT_WEBHOOK_RECEIVED,
	PAYMENT_VERIFIED,
	PAYMENT_FAILED,
	PAYMENT_MANUAL_SUBMITTED,
	PAYMENT_MANUAL_APPROVED,
	PAYMENT_MANUAL_REJECTED,
	LOGIN_FAILED,
	THROTTLE_TRIGGERED,
	SUSPICIOUS_ACTIVITY,
	SESSION_STARTED,
	SESSION_ENDED,
	PAGE_VIEW,
	INTERVIEW_STARTED,
	INTERVIEW_SAVED,
	INTERVIEW_SUBMITTED,
	INTERVIEW_ABANDONED,
	REPORT_VIEWED,
	REPORT_VIEW_FAILED,
	BILLING_PAGE_VIEWED,
	CREDIT_PURCHASE_INITIATED,
	RAPID_PAGE_REQUESTS,
	BOT_SUSPECTED,
	BILLING_SUBSCRIPTION_APPLIED,
	BILLING_QA_BYPASS_APPLIED,
]

SEVERITY_INFO = "INFO"
SEVERITY_WARNING = "WARNING"
SEVERITY_CRITICAL = "CRITICAL"

SEVERITY_CHOICES = [
	(SEVERITY_INFO, "Info"),
	(SEVERITY_WARNING, "Warning"),
	(SEVERITY_CRITICAL, "Critical"),
]

EVENT_TYPE_CHOICES = [(event_type, event_type.replace("_", " ").title()) for event_type in CANONICAL_EVENT_TYPES]