# Generated by Django 6.0.2 on 2026-02-19 01:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_credittransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='credittransaction',
            constraint=models.CheckConstraint(condition=models.Q(('type', 'purchase'), ('expiry_date__isnull', False), ('amount__gt', 0)), name='purchase_rule'),
        ),
        migrations.AddConstraint(
            model_name='credittransaction',
            constraint=models.CheckConstraint(condition=models.Q(('type', 'usage'), ('expiry_date__isnull', True), ('amount__lt', 0)), name='usage_rule'),
        ),
        migrations.AddConstraint(
            model_name='credittransaction',
            constraint=models.CheckConstraint(condition=models.Q(('type', 'refund'), ('expiry_date__isnull', True), ('amount__gt', 0)), name='refund_rule'),
        ),
        migrations.AddConstraint(
            model_name='credittransaction',
            constraint=models.CheckConstraint(condition=models.Q(('type', 'admin_adjustment'), ('expiry_date__isnull', True)), name='admin_adjustment_rule'),
        ),
    ]
