# Generated by Django 6.0.2 on 2026-02-19 02:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_credittransaction_purchase_rule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='credittransaction',
            name='purchase_rule',
        ),
        migrations.RemoveConstraint(
            model_name='credittransaction',
            name='usage_rule',
        ),
        migrations.RemoveConstraint(
            model_name='credittransaction',
            name='refund_rule',
        ),
        migrations.RemoveConstraint(
            model_name='credittransaction',
            name='admin_adjustment_rule',
        ),
        migrations.AddConstraint(
            model_name='credittransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 'purchase'), _negated=True), models.Q(('expiry_date__isnull', False), ('amount__gt', 0)), _connector='OR'), name='purchase_rule'),
        ),
        migrations.AddConstraint(
            model_name='credittransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 'usage'), _negated=True), models.Q(('expiry_date__isnull', True), ('amount__lt', 0)), _connector='OR'), name='usage_rule'),
        ),
        migrations.AddConstraint(
            model_name='credittransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 'refund'), _negated=True), models.Q(('expiry_date__isnull', True), ('amount__gt', 0)), _connector='OR'), name='refund_rule'),
        ),
        migrations.AddConstraint(
            model_name='credittransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 'admin_adjustment'), _negated=True), ('expiry_date__isnull', True), _connector='OR'), name='admin_adjustment_rule'),
        ),
    ]
