# Generated by Django 5.2.6 on 2026-03-27 04:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_subscription_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_key', models.CharField(choices=[('single', 'Single'), ('bundle_3', 'Bundle 3'), ('bundle_5', 'Bundle 5')], max_length=20)),
                ('amount_php', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('credits_purchased', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('payment_method', models.CharField(choices=[('GCASH', 'GCash'), ('MAYA', 'Maya')], max_length=10)),
                ('reference_number', models.CharField(max_length=120)),
                ('reference_number_normalized', models.CharField(max_length=120, unique=True)),
                ('reference_note', models.CharField(blank=True, max_length=255)),
                ('proof_file', models.FileField(upload_to='manual_payments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'pdf'])])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('credit_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_payment_records', to='billing.creditpurchase')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_payments_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
