# Generated by Django 6.0.2 on 2026-02-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(unique=True)),
                ('timestamp_utc', models.DateTimeField()),
                ('structure_version', models.CharField(max_length=10)),
                ('total_score', models.FloatField()),
                ('risk_band', models.CharField(max_length=20)),
                ('category_breakdown', models.JSONField()),
                ('license_to_sell_present', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
