# Generated by Django 5.2.6 on 2026-03-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='information_gaps',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='report',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='signals',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='report',
            name='suggestions',
            field=models.JSONField(default=list),
        ),
    ]
