# Generated by Django 5.2.6 on 2026-03-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_add_explanation_fields_and_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
