# Generated by Django 6.0.2 on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_add_city_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='assessment_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='strengths',
            field=models.JSONField(default=list),
        ),
    ]
