# Generated by Django 6.0.2 on 2026-02-24 03:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('EVALUATION_ATTEMPT', 'Evaluation Attempt'), ('EVALUATION_SUCCESS', 'Evaluation Success'), ('EVALUATION_VALIDATION_FAIL', 'Evaluation Validation Fail'), ('BILLING_SUBSCRIPTION_APPLIED', 'Billing Subscription Applied'), ('BILLING_CREDIT_DEDUCTED', 'Billing Credit Deducted'), ('BILLING_INSUFFICIENT_CREDIT', 'Billing Insufficient Credit'), ('THROTTLE_TRIGGERED', 'Throttle Triggered')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=10)),
                ('request_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
