# Generated by Django 5.2.6 on 2026-03-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('EVALUATION_ATTEMPT', 'Evaluation Attempt'), ('EVALUATION_SUCCESS', 'Evaluation Success'), ('EVALUATION_VALIDATION_FAIL', 'Evaluation Validation Fail'), ('BILLING_CREDIT_DEDUCTED', 'Billing Credit Deducted'), ('BILLING_INSUFFICIENT_CREDIT', 'Billing Insufficient Credit'), ('CREDIT_PURCHASE_CREATED', 'Credit Purchase Created'), ('PAYMENT_WEBHOOK_RECEIVED', 'Payment Webhook Received'), ('PAYMENT_VERIFIED', 'Payment Verified'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_MANUAL_SUBMITTED', 'Payment Manual Submitted'), ('PAYMENT_MANUAL_APPROVED', 'Payment Manual Approved'), ('PAYMENT_MANUAL_REJECTED', 'Payment Manual Rejected'), ('CONTACT_MESSAGE_SUBMITTED', 'Contact Message Submitted'), ('LOGIN_FAILED', 'Login Failed'), ('THROTTLE_TRIGGERED', 'Throttle Triggered'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity'), ('SESSION_STARTED', 'Session Started'), ('SESSION_ENDED', 'Session Ended'), ('PAGE_VIEW', 'Page View'), ('INTERVIEW_STARTED', 'Interview Started'), ('INTERVIEW_SAVED', 'Interview Saved'), ('INTERVIEW_SUBMITTED', 'Interview Submitted'), ('INTERVIEW_ABANDONED', 'Interview Abandoned'), ('REPORT_VIEWED', 'Report Viewed'), ('REPORT_VIEW_FAILED', 'Report View Failed'), ('BILLING_PAGE_VIEWED', 'Billing Page Viewed'), ('CREDIT_PURCHASE_INITIATED', 'Credit Purchase Initiated'), ('RAPID_PAGE_REQUESTS', 'Rapid Page Requests'), ('BOT_SUSPECTED', 'Bot Suspected'), ('BILLING_SUBSCRIPTION_APPLIED', 'Billing Subscription Applied'), ('BILLING_QA_BYPASS_APPLIED', 'Billing Qa Bypass Applied')], db_index=True, max_length=50),
        ),
    ]
