"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse, unquote
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

load_dotenv(BASE_DIR / ".env")


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default

    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=None):
    value = os.environ.get(name)
    if value is None:
        return list(default or [])

    return [item.strip() for item in value.split(",") if item.strip()]


def build_database_config():
    database_url = os.environ.get("DATABASE_URL")

    if database_url:
        parsed = urlparse(database_url)
        engine_map = {
            "postgres": "django.db.backends.postgresql",
            "postgresql": "django.db.backends.postgresql",
        }

        config = {
            "ENGINE": engine_map.get(parsed.scheme, "django.db.backends.postgresql"),
            "NAME": unquote(parsed.path.lstrip("/")),
            "USER": unquote(parsed.username or ""),
            "PASSWORD": unquote(parsed.password or ""),
            "HOST": parsed.hostname or "",
            "PORT": str(parsed.port or ""),
        }

        sslmode = os.environ.get("DB_SSLMODE")
        if sslmode:
            config["OPTIONS"] = {"sslmode": sslmode}

        return config

    config = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT'),
    }

    sslmode = os.environ.get("DB_SSLMODE")
    if sslmode:
        config["OPTIONS"] = {"sslmode": sslmode}

    return config



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.environ.get("SECRET_KEY")



# SECURITY WARNING: don't run with debug turned on in production!


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'billing',
    'contact',
    'idempotency',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'audit',
    'django.contrib.staticfiles',

    "reports",
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

DATABASES = {
    'default': build_database_config()
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Asia/Manila"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'





REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'config.exceptions.custom_exception_handler',
    
       # NOTE:
        # SessionAuthentication enabled for local dev testing only.
        # Must be removed before production deployment.

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        
    ),
 
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    #    'DEFAULT_THROTTLE_CLASSES': [
    #    'rest_framework.throttling.UserRateThrottle',
    #    'rest_framework.throttling.AnonRateThrottle',
    #],
    #    'DEFAULT_THROTTLE_RATES': {
    #    'user': '100/hour',
    #    'anon': '20/hour',
    #},

    'DEFAULT_RENDERER_CLASSES': (
    'rest_framework.renderers.JSONRenderer',
),

}


from datetime import timedelta

SIMPLE_JWT = {
    # Access token lifetime (short-lived)
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),

    # Refresh token lifetime (longer-lived)
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),

    # Rotate refresh tokens on use
    "ROTATE_REFRESH_TOKENS": True,

    # Blacklist old refresh tokens after rotation
    "BLACKLIST_AFTER_ROTATION": True,

    # Use secure algorithm
    "ALGORITHM": "HS256",

    # Require token type verification
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
}

LOGIN_REDIRECT_URL = "/"

# Email settings
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.environ.get("EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "25"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", False)
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", False)
EMAIL_TIMEOUT = int(os.environ.get("EMAIL_TIMEOUT", "10"))
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "RERA <onboarding@resend.dev>")
CONTACT_ADMIN_EMAIL = os.environ.get("CONTACT_ADMIN_EMAIL", "admin.heptageeks@gmail.com")
RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "")
RESEND_FROM_EMAIL = os.environ.get("RESEND_FROM_EMAIL", "RERA <onboarding@resend.dev>")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "[{asctime}] {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
        "error_file": {
        "class": "logging.FileHandler",
        "filename": BASE_DIR / "logs" / "errors.log",
        "level": "ERROR",
        "formatter": "standard",
        },
    },

        "root": {
        "handlers": ["console", "error_file"],
        "level": "INFO",
    },
    
    "loggers": {
        "django.server": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console", "error_file"],
            "level": "ERROR",
            "propagate": False,
        },
        
    },
}

CORS_ALLOW_ALL_ORIGINS = env_bool("CORS_ALLOW_ALL_ORIGINS", False)
CORS_ALLOWED_ORIGINS = env_list("CORS_ALLOWED_ORIGINS")
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS")
CORS_ALLOW_CREDENTIALS = True

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = env_bool("USE_X_FORWARDED_HOST", True)
SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", False)
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", False)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", False)
SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", False)
SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", False)

# ===== PayMongo Configuration =====

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

# ----- PayMongo Configuration -----
PAYMONGO_PUBLIC_KEY = os.getenv("PAYMONGO_PUBLIC_KEY")
PAYMONGO_SECRET_KEY = os.getenv("PAYMONGO_SECRET_KEY")
PAYMONGO_WEBHOOK_SECRET = os.getenv("PAYMONGO_WEBHOOK_SECRET")
PAYMONGO_CHECKOUT_FRONTEND_ORIGIN = os.getenv("PAYMONGO_CHECKOUT_FRONTEND_ORIGIN")
PAYMONGO_CHECKOUT_SUCCESS_URL = os.getenv("PAYMONGO_CHECKOUT_SUCCESS_URL")
PAYMONGO_CHECKOUT_CANCEL_URL = os.getenv("PAYMONGO_CHECKOUT_CANCEL_URL")
PAYMONGO_ENABLED = env_bool("PAYMONGO_ENABLED", True)

# Manual payment instructions
GCASH_NUMBER = os.getenv("GCASH_NUMBER", "")
GCASH_NAME = os.getenv("GCASH_NAME", "")
GCASH_QR_URL = os.getenv("GCASH_QR_URL", "")
MAYA_NUMBER = os.getenv("MAYA_NUMBER", "")
MAYA_NAME = os.getenv("MAYA_NAME", "")
MAYA_QR_URL = os.getenv("MAYA_QR_URL", "")
ADMIN_EMAIL = os.getenv("ADMIN_EMAIL", "")

# Temporary QA switch to bypass report paywall and credit deduction checks.
QA_BYPASS_UNLOCK = env_bool("QA_BYPASS_UNLOCK", False)
